apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator 
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
  namespace: apps
  labels:
    app: mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator
  template:
    metadata:
      labels:
        app: mediator
    spec:
      containers:
      - name: mediator
        image: michalwit/spring-mediator:1.3
        ports:
        - containerPort: 8080
