apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: apps
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
  loadBalancerIP: 35.207.67.175
